#! /bin/bash

# Copyright (c) 2019, Thomas Museus Dabay
# License: GNU General Public License Version 3 (GPL3)
#           https://www.gnu.org/licenses/gpl.html

# Connect JBL Flip 3 Speaker (use btint if mouse interferes with speaker)
#

#Connect JBL Flip 3 Speaker
echo -e 'connect FC:A8:9A:DE:75:1D\n' | bluetoothctl
sleep 10s
echo -e 'quit\n' | bluetoothctl

#Set PulseAudio to Use Flip 3
if pactl set-default-sink bluez_sink.FC_A8_9A_DE_75_1D.a2dp_sink
	then exit 0
else
	echo 'Error: PulseAudio setup failed'
	exit 1
fi
